# Generated by Django 3.2.3 on 2022-01-04 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=70, verbose_name='Адрес')),
                ('schedule', models.CharField(max_length=150, verbose_name='График работы')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Эффект')),
                ('text', models.TextField(max_length=250, verbose_name='Описание эффекта')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('on_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
            ],
            options={
                'verbose_name': 'Эффект',
                'verbose_name_plural': 'Эффекты',
            },
        ),
        migrations.CreateModel(
            name='HowItWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст')),
                ('on_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
            ],
            options={
                'verbose_name': 'Как это работает',
                'verbose_name_plural': 'Как это работает',
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Главная информация',
                'verbose_name_plural': 'Главная информация',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('abon', 'Абонемент'), ('card', 'Клубная карта'), ('gift', 'Подарочный сертификат')], max_length=4, verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Продолжительность')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('moderated', models.BooleanField(default=False, verbose_name='Отзыв проверен')),
                ('on_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Продолжительность')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка')),
                ('on_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
