# Generated by Django 3.2.3 on 2022-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='info',
            field=models.TextField(default=1, max_length=150, verbose_name='Инфо'),
            preserve_default=False,
        ),
    ]
